/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#include "analogin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esmp_v1_analogin_AnalogInAdd, esmp_v1_analogin_AnalogInAdd, AUTO)


PB_BIND(esmp_v1_analogin_AnalogInRemove, esmp_v1_analogin_AnalogInRemove, AUTO)


PB_BIND(esmp_v1_analogin_AnalogInEvent, esmp_v1_analogin_AnalogInEvent, AUTO)



