/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#ifndef PB_ESMP_V1_ANALOGIN_ANALOGIN_PB_H_INCLUDED
#define PB_ESMP_V1_ANALOGIN_ANALOGIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _esmp_v1_analogin_AnalogInAdd {
    char pin_name[33];
    float sample_mode_poll_period;
} esmp_v1_analogin_AnalogInAdd;

typedef struct _esmp_v1_analogin_AnalogInEvent {
    char pin_name[33];
    float value;
} esmp_v1_analogin_AnalogInEvent;

typedef struct _esmp_v1_analogin_AnalogInRemove {
    char pin_name[33];
} esmp_v1_analogin_AnalogInRemove;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esmp_v1_analogin_AnalogInAdd_init_default {"", 0}
#define esmp_v1_analogin_AnalogInRemove_init_default {""}
#define esmp_v1_analogin_AnalogInEvent_init_default {"", 0}
#define esmp_v1_analogin_AnalogInAdd_init_zero   {"", 0}
#define esmp_v1_analogin_AnalogInRemove_init_zero {""}
#define esmp_v1_analogin_AnalogInEvent_init_zero {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define esmp_v1_analogin_AnalogInAdd_pin_name_tag 1
#define esmp_v1_analogin_AnalogInAdd_sample_mode_poll_period_tag 3
#define esmp_v1_analogin_AnalogInEvent_pin_name_tag 1
#define esmp_v1_analogin_AnalogInEvent_value_tag 2
#define esmp_v1_analogin_AnalogInRemove_pin_name_tag 1

/* Struct field encoding specification for nanopb */
#define esmp_v1_analogin_AnalogInAdd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    sample_mode_poll_period,   3)
#define esmp_v1_analogin_AnalogInAdd_CALLBACK NULL
#define esmp_v1_analogin_AnalogInAdd_DEFAULT NULL

#define esmp_v1_analogin_AnalogInRemove_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1)
#define esmp_v1_analogin_AnalogInRemove_CALLBACK NULL
#define esmp_v1_analogin_AnalogInRemove_DEFAULT NULL

#define esmp_v1_analogin_AnalogInEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define esmp_v1_analogin_AnalogInEvent_CALLBACK NULL
#define esmp_v1_analogin_AnalogInEvent_DEFAULT NULL

extern const pb_msgdesc_t esmp_v1_analogin_AnalogInAdd_msg;
extern const pb_msgdesc_t esmp_v1_analogin_AnalogInRemove_msg;
extern const pb_msgdesc_t esmp_v1_analogin_AnalogInEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esmp_v1_analogin_AnalogInAdd_fields &esmp_v1_analogin_AnalogInAdd_msg
#define esmp_v1_analogin_AnalogInRemove_fields &esmp_v1_analogin_AnalogInRemove_msg
#define esmp_v1_analogin_AnalogInEvent_fields &esmp_v1_analogin_AnalogInEvent_msg

/* Maximum encoded size of messages (where known) */
#define esmp_v1_analogin_AnalogInAdd_size        39
#define esmp_v1_analogin_AnalogInRemove_size     34
#define esmp_v1_analogin_AnalogInEvent_size      39

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
