/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#ifndef PB_ESMP_V1_GPIO_GPIO_PB_H_INCLUDED
#define PB_ESMP_V1_GPIO_GPIO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _esmp_v1_gpio_GPIODirection {
    esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_UNSPECIFIED = 0,
    esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_INPUT = 1,
    esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_INPUT_PULL_UP = 2,
    esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_OUTPUT = 3
} esmp_v1_gpio_GPIODirection;

typedef enum _esmp_v1_gpio_GPIOSampleMode {
    esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_UNSPECIFIED = 0,
    esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_POLL = 1,
    esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_EVENT = 2
} esmp_v1_gpio_GPIOSampleMode;

/* Struct definitions */
typedef struct _esmp_v1_gpio_GPIOAdd {
    char pin_name[33];
    esmp_v1_gpio_GPIODirection direction;
    esmp_v1_gpio_GPIOSampleMode sample_mode;
    float sample_mode_poll_period;
} esmp_v1_gpio_GPIOAdd;

typedef struct _esmp_v1_gpio_GPIOAdded {
    char pin_name[33];
} esmp_v1_gpio_GPIOAdded;

typedef struct _esmp_v1_gpio_GPIOEvent {
    char pin_name[33];
    bool value;
} esmp_v1_gpio_GPIOEvent;

typedef struct _esmp_v1_gpio_GPIORemove {
    char pin_name[33];
} esmp_v1_gpio_GPIORemove;

typedef struct _esmp_v1_gpio_GPIORemoved {
    char pin_name[33];
} esmp_v1_gpio_GPIORemoved;

typedef struct _esmp_v1_gpio_GPIOWrite {
    char pin_name[33];
    bool value;
} esmp_v1_gpio_GPIOWrite;


/* Helper constants for enums */
#define _esmp_v1_gpio_GPIODirection_MIN esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_UNSPECIFIED
#define _esmp_v1_gpio_GPIODirection_MAX esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_OUTPUT
#define _esmp_v1_gpio_GPIODirection_ARRAYSIZE ((esmp_v1_gpio_GPIODirection)(esmp_v1_gpio_GPIODirection_GPIO_DIRECTION_OUTPUT+1))

#define _esmp_v1_gpio_GPIOSampleMode_MIN esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_UNSPECIFIED
#define _esmp_v1_gpio_GPIOSampleMode_MAX esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_EVENT
#define _esmp_v1_gpio_GPIOSampleMode_ARRAYSIZE ((esmp_v1_gpio_GPIOSampleMode)(esmp_v1_gpio_GPIOSampleMode_GPIO_SAMPLE_MODE_EVENT+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esmp_v1_gpio_GPIOAdd_init_default        {"", _esmp_v1_gpio_GPIODirection_MIN, _esmp_v1_gpio_GPIOSampleMode_MIN, 0}
#define esmp_v1_gpio_GPIOAdded_init_default      {""}
#define esmp_v1_gpio_GPIORemove_init_default     {""}
#define esmp_v1_gpio_GPIORemoved_init_default    {""}
#define esmp_v1_gpio_GPIOWrite_init_default      {"", 0}
#define esmp_v1_gpio_GPIOEvent_init_default      {"", 0}
#define esmp_v1_gpio_GPIOAdd_init_zero           {"", _esmp_v1_gpio_GPIODirection_MIN, _esmp_v1_gpio_GPIOSampleMode_MIN, 0}
#define esmp_v1_gpio_GPIOAdded_init_zero         {""}
#define esmp_v1_gpio_GPIORemove_init_zero        {""}
#define esmp_v1_gpio_GPIORemoved_init_zero       {""}
#define esmp_v1_gpio_GPIOWrite_init_zero         {"", 0}
#define esmp_v1_gpio_GPIOEvent_init_zero         {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define esmp_v1_gpio_GPIOAdd_pin_name_tag        1
#define esmp_v1_gpio_GPIOAdd_direction_tag       2
#define esmp_v1_gpio_GPIOAdd_sample_mode_tag     3
#define esmp_v1_gpio_GPIOAdd_sample_mode_poll_period_tag 4
#define esmp_v1_gpio_GPIOAdded_pin_name_tag      1
#define esmp_v1_gpio_GPIOEvent_pin_name_tag      1
#define esmp_v1_gpio_GPIOEvent_value_tag         2
#define esmp_v1_gpio_GPIORemove_pin_name_tag     1
#define esmp_v1_gpio_GPIORemoved_pin_name_tag    1
#define esmp_v1_gpio_GPIOWrite_pin_name_tag      1
#define esmp_v1_gpio_GPIOWrite_value_tag         2

/* Struct field encoding specification for nanopb */
#define esmp_v1_gpio_GPIOAdd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         2) \
X(a, STATIC,   SINGULAR, UENUM,    sample_mode,       3) \
X(a, STATIC,   SINGULAR, FLOAT,    sample_mode_poll_period,   4)
#define esmp_v1_gpio_GPIOAdd_CALLBACK NULL
#define esmp_v1_gpio_GPIOAdd_DEFAULT NULL

#define esmp_v1_gpio_GPIOAdded_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1)
#define esmp_v1_gpio_GPIOAdded_CALLBACK NULL
#define esmp_v1_gpio_GPIOAdded_DEFAULT NULL

#define esmp_v1_gpio_GPIORemove_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1)
#define esmp_v1_gpio_GPIORemove_CALLBACK NULL
#define esmp_v1_gpio_GPIORemove_DEFAULT NULL

#define esmp_v1_gpio_GPIORemoved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1)
#define esmp_v1_gpio_GPIORemoved_CALLBACK NULL
#define esmp_v1_gpio_GPIORemoved_DEFAULT NULL

#define esmp_v1_gpio_GPIOWrite_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1) \
X(a, STATIC,   SINGULAR, BOOL,     value,             2)
#define esmp_v1_gpio_GPIOWrite_CALLBACK NULL
#define esmp_v1_gpio_GPIOWrite_DEFAULT NULL

#define esmp_v1_gpio_GPIOEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin_name,          1) \
X(a, STATIC,   SINGULAR, BOOL,     value,             2)
#define esmp_v1_gpio_GPIOEvent_CALLBACK NULL
#define esmp_v1_gpio_GPIOEvent_DEFAULT NULL

extern const pb_msgdesc_t esmp_v1_gpio_GPIOAdd_msg;
extern const pb_msgdesc_t esmp_v1_gpio_GPIOAdded_msg;
extern const pb_msgdesc_t esmp_v1_gpio_GPIORemove_msg;
extern const pb_msgdesc_t esmp_v1_gpio_GPIORemoved_msg;
extern const pb_msgdesc_t esmp_v1_gpio_GPIOWrite_msg;
extern const pb_msgdesc_t esmp_v1_gpio_GPIOEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esmp_v1_gpio_GPIOAdd_fields &esmp_v1_gpio_GPIOAdd_msg
#define esmp_v1_gpio_GPIOAdded_fields &esmp_v1_gpio_GPIOAdded_msg
#define esmp_v1_gpio_GPIORemove_fields &esmp_v1_gpio_GPIORemove_msg
#define esmp_v1_gpio_GPIORemoved_fields &esmp_v1_gpio_GPIORemoved_msg
#define esmp_v1_gpio_GPIOWrite_fields &esmp_v1_gpio_GPIOWrite_msg
#define esmp_v1_gpio_GPIOEvent_fields &esmp_v1_gpio_GPIOEvent_msg

/* Maximum encoded size of messages (where known) */
#define esmp_v1_gpio_GPIOAdd_size                43
#define esmp_v1_gpio_GPIOAdded_size              34
#define esmp_v1_gpio_GPIORemove_size             34
#define esmp_v1_gpio_GPIORemoved_size            34
#define esmp_v1_gpio_GPIOWrite_size              36
#define esmp_v1_gpio_GPIOEvent_size              36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
