/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#include "gpio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esmp_v1_gpio_GPIOAdd, esmp_v1_gpio_GPIOAdd, AUTO)


PB_BIND(esmp_v1_gpio_GPIOAdded, esmp_v1_gpio_GPIOAdded, AUTO)


PB_BIND(esmp_v1_gpio_GPIORemove, esmp_v1_gpio_GPIORemove, AUTO)


PB_BIND(esmp_v1_gpio_GPIORemoved, esmp_v1_gpio_GPIORemoved, AUTO)


PB_BIND(esmp_v1_gpio_GPIOWrite, esmp_v1_gpio_GPIOWrite, AUTO)


PB_BIND(esmp_v1_gpio_GPIOEvent, esmp_v1_gpio_GPIOEvent, AUTO)





