/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#ifndef PB_ESMP_V1_REGISTER_REGISTER_PB_H_INCLUDED
#define PB_ESMP_V1_REGISTER_REGISTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _esmp_v1_register_RegisterAdd {
    char device_identifier[33];
} esmp_v1_register_RegisterAdd;

typedef struct _esmp_v1_register_RegisterAdded {
    char device_identifier[33];
    uint32_t pin_cnt_digital;
    uint32_t pin_cnt_analog;
} esmp_v1_register_RegisterAdded;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esmp_v1_register_RegisterAdd_init_default {""}
#define esmp_v1_register_RegisterAdded_init_default {"", 0, 0}
#define esmp_v1_register_RegisterAdd_init_zero   {""}
#define esmp_v1_register_RegisterAdded_init_zero {"", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define esmp_v1_register_RegisterAdd_device_identifier_tag 1
#define esmp_v1_register_RegisterAdded_device_identifier_tag 1
#define esmp_v1_register_RegisterAdded_pin_cnt_digital_tag 2
#define esmp_v1_register_RegisterAdded_pin_cnt_analog_tag 3

/* Struct field encoding specification for nanopb */
#define esmp_v1_register_RegisterAdd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_identifier,   1)
#define esmp_v1_register_RegisterAdd_CALLBACK NULL
#define esmp_v1_register_RegisterAdd_DEFAULT NULL

#define esmp_v1_register_RegisterAdded_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_identifier,   1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_cnt_digital,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pin_cnt_analog,    3)
#define esmp_v1_register_RegisterAdded_CALLBACK NULL
#define esmp_v1_register_RegisterAdded_DEFAULT NULL

extern const pb_msgdesc_t esmp_v1_register_RegisterAdd_msg;
extern const pb_msgdesc_t esmp_v1_register_RegisterAdded_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esmp_v1_register_RegisterAdd_fields &esmp_v1_register_RegisterAdd_msg
#define esmp_v1_register_RegisterAdded_fields &esmp_v1_register_RegisterAdded_msg

/* Maximum encoded size of messages (where known) */
#define esmp_v1_register_RegisterAdd_size        34
#define esmp_v1_register_RegisterAdded_size      46

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
