/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 11:07:55 2025. */

#include "register.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(register_v1_gpio_RegisterAdd, register_v1_gpio_RegisterAdd, AUTO)


PB_BIND(register_v1_gpio_RegisterAdded, register_v1_gpio_RegisterAdded, AUTO)



