/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 11:07:55 2025. */

#ifndef PB_REGISTER_V1_GPIO_REGISTER_PB_H_INCLUDED
#define PB_REGISTER_V1_GPIO_REGISTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _register_v1_gpio_RegisterAdd {
    pb_callback_t device_identifier;
} register_v1_gpio_RegisterAdd;

typedef struct _register_v1_gpio_RegisterAdded {
    pb_callback_t device_identifier;
    uint32_t pin_cnt_digital;
    uint32_t pin_cnt_analog;
} register_v1_gpio_RegisterAdded;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define register_v1_gpio_RegisterAdd_init_default {{{NULL}, NULL}}
#define register_v1_gpio_RegisterAdded_init_default {{{NULL}, NULL}, 0, 0}
#define register_v1_gpio_RegisterAdd_init_zero   {{{NULL}, NULL}}
#define register_v1_gpio_RegisterAdded_init_zero {{{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define register_v1_gpio_RegisterAdd_device_identifier_tag 1
#define register_v1_gpio_RegisterAdded_device_identifier_tag 1
#define register_v1_gpio_RegisterAdded_pin_cnt_digital_tag 2
#define register_v1_gpio_RegisterAdded_pin_cnt_analog_tag 3

/* Struct field encoding specification for nanopb */
#define register_v1_gpio_RegisterAdd_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_identifier,   1)
#define register_v1_gpio_RegisterAdd_CALLBACK pb_default_field_callback
#define register_v1_gpio_RegisterAdd_DEFAULT NULL

#define register_v1_gpio_RegisterAdded_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_identifier,   1) \
X(a, STATIC,   SINGULAR, UINT32,   pin_cnt_digital,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pin_cnt_analog,    3)
#define register_v1_gpio_RegisterAdded_CALLBACK pb_default_field_callback
#define register_v1_gpio_RegisterAdded_DEFAULT NULL

extern const pb_msgdesc_t register_v1_gpio_RegisterAdd_msg;
extern const pb_msgdesc_t register_v1_gpio_RegisterAdded_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define register_v1_gpio_RegisterAdd_fields &register_v1_gpio_RegisterAdd_msg
#define register_v1_gpio_RegisterAdded_fields &register_v1_gpio_RegisterAdded_msg

/* Maximum encoded size of messages (where known) */
/* register_v1_gpio_RegisterAdd_size depends on runtime parameters */
/* register_v1_gpio_RegisterAdded_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
