/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 12:30:48 2025. */

#include "register.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esmp_v1_register_RegisterAdd, esmp_v1_register_RegisterAdd, AUTO)


PB_BIND(esmp_v1_register_RegisterAdded, esmp_v1_register_RegisterAdded, AUTO)



