/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#include "signal.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esmp_v1_SignalRequest, esmp_v1_SignalRequest, AUTO)


PB_BIND(esmp_v1_SignalResponse, esmp_v1_SignalResponse, AUTO)



