/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 11:07:55 2025. */

#ifndef PB_ESMP_V1_SIGNAL_PB_H_INCLUDED
#define PB_ESMP_V1_SIGNAL_PB_H_INCLUDED
#include <pb.h>
#include "gpio.pb.h"
#include "register.pb.h"
#include "temperature.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _esmp_v1_SignalRequest {
    pb_size_t which_payload;
    union {
        register_v1_gpio_RegisterAdd register_add;
        esmp_v1_gpio_GPIOAdd gpio_add;
        esmp_v1_gpio_GPIORemove gpio_remove;
        esmp_v1_gpio_GPIOWrite gpio_write;
        temperature_v1_gpio_TemperatureSensorAdd temp_sensor_add;
    } payload;
} esmp_v1_SignalRequest;

typedef struct _esmp_v1_SignalResponse {
    pb_size_t which_payload;
    union {
        register_v1_gpio_RegisterAdded register_added;
        esmp_v1_gpio_GPIOAdded gpio_added;
        esmp_v1_gpio_GPIORemoved gpio_removed;
        esmp_v1_gpio_GPIOEvent gpio_event;
        temperature_v1_gpio_TemperatureSensorAdded temp_sensor_added;
        temperature_v1_gpio_TemperatureSensorEvent temp_sensor_event;
    } payload;
} esmp_v1_SignalResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esmp_v1_SignalRequest_init_default       {0, {register_v1_gpio_RegisterAdd_init_default}}
#define esmp_v1_SignalResponse_init_default      {0, {register_v1_gpio_RegisterAdded_init_default}}
#define esmp_v1_SignalRequest_init_zero          {0, {register_v1_gpio_RegisterAdd_init_zero}}
#define esmp_v1_SignalResponse_init_zero         {0, {register_v1_gpio_RegisterAdded_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define esmp_v1_SignalRequest_register_add_tag   1
#define esmp_v1_SignalRequest_gpio_add_tag       2
#define esmp_v1_SignalRequest_gpio_remove_tag    3
#define esmp_v1_SignalRequest_gpio_write_tag     4
#define esmp_v1_SignalRequest_temp_sensor_add_tag 5
#define esmp_v1_SignalResponse_register_added_tag 1
#define esmp_v1_SignalResponse_gpio_added_tag    2
#define esmp_v1_SignalResponse_gpio_removed_tag  3
#define esmp_v1_SignalResponse_gpio_event_tag    4
#define esmp_v1_SignalResponse_temp_sensor_added_tag 5
#define esmp_v1_SignalResponse_temp_sensor_event_tag 6

/* Struct field encoding specification for nanopb */
#define esmp_v1_SignalRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,register_add,payload.register_add),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_add,payload.gpio_add),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_remove,payload.gpio_remove),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_write,payload.gpio_write),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,temp_sensor_add,payload.temp_sensor_add),   5)
#define esmp_v1_SignalRequest_CALLBACK NULL
#define esmp_v1_SignalRequest_DEFAULT NULL
#define esmp_v1_SignalRequest_payload_register_add_MSGTYPE register_v1_gpio_RegisterAdd
#define esmp_v1_SignalRequest_payload_gpio_add_MSGTYPE esmp_v1_gpio_GPIOAdd
#define esmp_v1_SignalRequest_payload_gpio_remove_MSGTYPE esmp_v1_gpio_GPIORemove
#define esmp_v1_SignalRequest_payload_gpio_write_MSGTYPE esmp_v1_gpio_GPIOWrite
#define esmp_v1_SignalRequest_payload_temp_sensor_add_MSGTYPE temperature_v1_gpio_TemperatureSensorAdd

#define esmp_v1_SignalResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,register_added,payload.register_added),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_added,payload.gpio_added),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_removed,payload.gpio_removed),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpio_event,payload.gpio_event),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,temp_sensor_added,payload.temp_sensor_added),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,temp_sensor_event,payload.temp_sensor_event),   6)
#define esmp_v1_SignalResponse_CALLBACK NULL
#define esmp_v1_SignalResponse_DEFAULT NULL
#define esmp_v1_SignalResponse_payload_register_added_MSGTYPE register_v1_gpio_RegisterAdded
#define esmp_v1_SignalResponse_payload_gpio_added_MSGTYPE esmp_v1_gpio_GPIOAdded
#define esmp_v1_SignalResponse_payload_gpio_removed_MSGTYPE esmp_v1_gpio_GPIORemoved
#define esmp_v1_SignalResponse_payload_gpio_event_MSGTYPE esmp_v1_gpio_GPIOEvent
#define esmp_v1_SignalResponse_payload_temp_sensor_added_MSGTYPE temperature_v1_gpio_TemperatureSensorAdded
#define esmp_v1_SignalResponse_payload_temp_sensor_event_MSGTYPE temperature_v1_gpio_TemperatureSensorEvent

extern const pb_msgdesc_t esmp_v1_SignalRequest_msg;
extern const pb_msgdesc_t esmp_v1_SignalResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esmp_v1_SignalRequest_fields &esmp_v1_SignalRequest_msg
#define esmp_v1_SignalResponse_fields &esmp_v1_SignalResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(register_v1_gpio_RegisterAdd_size) && defined(esmp_v1_gpio_GPIOAdd_size) && defined(esmp_v1_gpio_GPIORemove_size) && defined(esmp_v1_gpio_GPIOWrite_size) && defined(temperature_v1_gpio_TemperatureSensorAdd_size)
union esmp_v1_SignalRequest_payload_size_union {char f1[(6 + register_v1_gpio_RegisterAdd_size)]; char f2[(6 + esmp_v1_gpio_GPIOAdd_size)]; char f3[(6 + esmp_v1_gpio_GPIORemove_size)]; char f4[(6 + esmp_v1_gpio_GPIOWrite_size)]; char f5[(6 + temperature_v1_gpio_TemperatureSensorAdd_size)];};
#define esmp_v1_SignalRequest_size               (0 + sizeof(union esmp_v1_SignalRequest_payload_size_union))
#endif
#if defined(register_v1_gpio_RegisterAdded_size) && defined(esmp_v1_gpio_GPIOAdded_size) && defined(esmp_v1_gpio_GPIORemoved_size) && defined(esmp_v1_gpio_GPIOEvent_size) && defined(temperature_v1_gpio_TemperatureSensorAdded_size) && defined(temperature_v1_gpio_TemperatureSensorEvent_size)
union esmp_v1_SignalResponse_payload_size_union {char f1[(6 + register_v1_gpio_RegisterAdded_size)]; char f2[(6 + esmp_v1_gpio_GPIOAdded_size)]; char f3[(6 + esmp_v1_gpio_GPIORemoved_size)]; char f4[(6 + esmp_v1_gpio_GPIOEvent_size)]; char f5[(6 + temperature_v1_gpio_TemperatureSensorAdded_size)]; char f6[(6 + temperature_v1_gpio_TemperatureSensorEvent_size)];};
#define esmp_v1_SignalResponse_size              (0 + sizeof(union esmp_v1_SignalResponse_payload_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
