/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Tue Feb 17 13:42:12 2026. */

#ifndef PB_ESMP_V1_SIGNAL_PB_H_INCLUDED
#define PB_ESMP_V1_SIGNAL_PB_H_INCLUDED
#include <pb.h>
#include "analogin.pb.h"
#include "gpio.pb.h"
#include "register.pb.h"
#include "temperature.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _esmp_v1_SignalRequest {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        esmp_v1_register_RegisterAdd register_add;
        esmp_v1_gpio_GPIOAdd gpio_add;
        esmp_v1_gpio_GPIORemove gpio_remove;
        esmp_v1_gpio_GPIOWrite gpio_write;
        temperature_v1_gpio_TemperatureSensorAdd temp_sensor_add;
        esmp_v1_analogin_AnalogInAdd analog_in_add;
        esmp_v1_analogin_AnalogInRemove analog_in_remove;
    } payload;
} esmp_v1_SignalRequest;

typedef struct _esmp_v1_SignalResponse {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        esmp_v1_register_RegisterAdded register_added;
        esmp_v1_gpio_GPIOAdded gpio_added;
        esmp_v1_gpio_GPIORemoved gpio_removed;
        esmp_v1_gpio_GPIOEvent gpio_event;
        temperature_v1_gpio_TemperatureSensorAdded temp_sensor_added;
        temperature_v1_gpio_TemperatureSensorEvent temp_sensor_event;
        esmp_v1_analogin_AnalogInEvent analog_in_event;
    } payload;
} esmp_v1_SignalResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define esmp_v1_SignalRequest_init_default       {{{NULL}, NULL}, 0, {esmp_v1_register_RegisterAdd_init_default}}
#define esmp_v1_SignalResponse_init_default      {{{NULL}, NULL}, 0, {esmp_v1_register_RegisterAdded_init_default}}
#define esmp_v1_SignalRequest_init_zero          {{{NULL}, NULL}, 0, {esmp_v1_register_RegisterAdd_init_zero}}
#define esmp_v1_SignalResponse_init_zero         {{{NULL}, NULL}, 0, {esmp_v1_register_RegisterAdded_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define esmp_v1_SignalRequest_register_add_tag   1
#define esmp_v1_SignalRequest_gpio_add_tag       2
#define esmp_v1_SignalRequest_gpio_remove_tag    3
#define esmp_v1_SignalRequest_gpio_write_tag     4
#define esmp_v1_SignalRequest_temp_sensor_add_tag 5
#define esmp_v1_SignalRequest_analog_in_add_tag  6
#define esmp_v1_SignalRequest_analog_in_remove_tag 7
#define esmp_v1_SignalResponse_register_added_tag 1
#define esmp_v1_SignalResponse_gpio_added_tag    2
#define esmp_v1_SignalResponse_gpio_removed_tag  3
#define esmp_v1_SignalResponse_gpio_event_tag    4
#define esmp_v1_SignalResponse_temp_sensor_added_tag 5
#define esmp_v1_SignalResponse_temp_sensor_event_tag 6
#define esmp_v1_SignalResponse_analog_in_event_tag 9

/* Struct field encoding specification for nanopb */
#define esmp_v1_SignalRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_add,payload.register_add),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_add,payload.gpio_add),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_remove,payload.gpio_remove),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_write,payload.gpio_write),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,temp_sensor_add,payload.temp_sensor_add),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,analog_in_add,payload.analog_in_add),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,analog_in_remove,payload.analog_in_remove),   7)
#define esmp_v1_SignalRequest_CALLBACK NULL
#define esmp_v1_SignalRequest_DEFAULT NULL
#define esmp_v1_SignalRequest_payload_register_add_MSGTYPE esmp_v1_register_RegisterAdd
#define esmp_v1_SignalRequest_payload_gpio_add_MSGTYPE esmp_v1_gpio_GPIOAdd
#define esmp_v1_SignalRequest_payload_gpio_remove_MSGTYPE esmp_v1_gpio_GPIORemove
#define esmp_v1_SignalRequest_payload_gpio_write_MSGTYPE esmp_v1_gpio_GPIOWrite
#define esmp_v1_SignalRequest_payload_temp_sensor_add_MSGTYPE temperature_v1_gpio_TemperatureSensorAdd
#define esmp_v1_SignalRequest_payload_analog_in_add_MSGTYPE esmp_v1_analogin_AnalogInAdd
#define esmp_v1_SignalRequest_payload_analog_in_remove_MSGTYPE esmp_v1_analogin_AnalogInRemove

#define esmp_v1_SignalResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_added,payload.register_added),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_added,payload.gpio_added),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_removed,payload.gpio_removed),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,gpio_event,payload.gpio_event),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,temp_sensor_added,payload.temp_sensor_added),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,temp_sensor_event,payload.temp_sensor_event),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,analog_in_event,payload.analog_in_event),   9)
#define esmp_v1_SignalResponse_CALLBACK NULL
#define esmp_v1_SignalResponse_DEFAULT NULL
#define esmp_v1_SignalResponse_payload_register_added_MSGTYPE esmp_v1_register_RegisterAdded
#define esmp_v1_SignalResponse_payload_gpio_added_MSGTYPE esmp_v1_gpio_GPIOAdded
#define esmp_v1_SignalResponse_payload_gpio_removed_MSGTYPE esmp_v1_gpio_GPIORemoved
#define esmp_v1_SignalResponse_payload_gpio_event_MSGTYPE esmp_v1_gpio_GPIOEvent
#define esmp_v1_SignalResponse_payload_temp_sensor_added_MSGTYPE temperature_v1_gpio_TemperatureSensorAdded
#define esmp_v1_SignalResponse_payload_temp_sensor_event_MSGTYPE temperature_v1_gpio_TemperatureSensorEvent
#define esmp_v1_SignalResponse_payload_analog_in_event_MSGTYPE esmp_v1_analogin_AnalogInEvent

extern const pb_msgdesc_t esmp_v1_SignalRequest_msg;
extern const pb_msgdesc_t esmp_v1_SignalResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esmp_v1_SignalRequest_fields &esmp_v1_SignalRequest_msg
#define esmp_v1_SignalResponse_fields &esmp_v1_SignalResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(temperature_v1_gpio_TemperatureSensorAdd_size)
union esmp_v1_SignalRequest_payload_size_union {char f5[(6 + temperature_v1_gpio_TemperatureSensorAdd_size)]; char f0[45];};
#define esmp_v1_SignalRequest_size               (0 + sizeof(union esmp_v1_SignalRequest_payload_size_union))
#endif
#if defined(temperature_v1_gpio_TemperatureSensorAdded_size) && defined(temperature_v1_gpio_TemperatureSensorEvent_size)
union esmp_v1_SignalResponse_payload_size_union {char f5[(6 + temperature_v1_gpio_TemperatureSensorAdded_size)]; char f6[(6 + temperature_v1_gpio_TemperatureSensorEvent_size)]; char f0[48];};
#define esmp_v1_SignalResponse_size              (0 + sizeof(union esmp_v1_SignalResponse_payload_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
