/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 11:07:55 2025. */

#include "temperature.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(temperature_v1_gpio_TemperatureSensorAdd, temperature_v1_gpio_TemperatureSensorAdd, AUTO)


PB_BIND(temperature_v1_gpio_TemperatureSensorAdded, temperature_v1_gpio_TemperatureSensorAdded, AUTO)


PB_BIND(temperature_v1_gpio_TemperatureSensorEvent, temperature_v1_gpio_TemperatureSensorEvent, AUTO)




