/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev at Fri Nov 14 12:30:48 2025. */

#ifndef PB_TEMPERATURE_V1_GPIO_TEMPERATURE_PB_H_INCLUDED
#define PB_TEMPERATURE_V1_GPIO_TEMPERATURE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _temperature_v1_gpio_TemperatureSensorUnit {
    temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_UNSPECIFIED = 0,
    temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_CELSIUS = 1,
    temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_FAHRENHEIT = 2
} temperature_v1_gpio_TemperatureSensorUnit;

/* Struct definitions */
typedef struct _temperature_v1_gpio_TemperatureSensorAdd {
    pb_callback_t sensor_pin;
    int32_t sensor_resolution;
} temperature_v1_gpio_TemperatureSensorAdd;

typedef struct _temperature_v1_gpio_TemperatureSensorAdded {
    pb_callback_t sensor_pin;
    bool did_add;
} temperature_v1_gpio_TemperatureSensorAdded;

typedef struct _temperature_v1_gpio_TemperatureSensorEvent {
    pb_callback_t sensor_pin;
    float temperature_celsius;
    float temperature_fahrenheit;
    temperature_v1_gpio_TemperatureSensorUnit si_unit;
} temperature_v1_gpio_TemperatureSensorEvent;


/* Helper constants for enums */
#define _temperature_v1_gpio_TemperatureSensorUnit_MIN temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_UNSPECIFIED
#define _temperature_v1_gpio_TemperatureSensorUnit_MAX temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_FAHRENHEIT
#define _temperature_v1_gpio_TemperatureSensorUnit_ARRAYSIZE ((temperature_v1_gpio_TemperatureSensorUnit)(temperature_v1_gpio_TemperatureSensorUnit_TEMPERATURE_SENSOR_UNIT_FAHRENHEIT+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define temperature_v1_gpio_TemperatureSensorAdd_init_default {{{NULL}, NULL}, 0}
#define temperature_v1_gpio_TemperatureSensorAdded_init_default {{{NULL}, NULL}, 0}
#define temperature_v1_gpio_TemperatureSensorEvent_init_default {{{NULL}, NULL}, 0, 0, _temperature_v1_gpio_TemperatureSensorUnit_MIN}
#define temperature_v1_gpio_TemperatureSensorAdd_init_zero {{{NULL}, NULL}, 0}
#define temperature_v1_gpio_TemperatureSensorAdded_init_zero {{{NULL}, NULL}, 0}
#define temperature_v1_gpio_TemperatureSensorEvent_init_zero {{{NULL}, NULL}, 0, 0, _temperature_v1_gpio_TemperatureSensorUnit_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define temperature_v1_gpio_TemperatureSensorAdd_sensor_pin_tag 1
#define temperature_v1_gpio_TemperatureSensorAdd_sensor_resolution_tag 2
#define temperature_v1_gpio_TemperatureSensorAdded_sensor_pin_tag 1
#define temperature_v1_gpio_TemperatureSensorAdded_did_add_tag 2
#define temperature_v1_gpio_TemperatureSensorEvent_sensor_pin_tag 1
#define temperature_v1_gpio_TemperatureSensorEvent_temperature_celsius_tag 2
#define temperature_v1_gpio_TemperatureSensorEvent_temperature_fahrenheit_tag 3
#define temperature_v1_gpio_TemperatureSensorEvent_si_unit_tag 4

/* Struct field encoding specification for nanopb */
#define temperature_v1_gpio_TemperatureSensorAdd_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_pin,        1) \
X(a, STATIC,   SINGULAR, INT32,    sensor_resolution,   2)
#define temperature_v1_gpio_TemperatureSensorAdd_CALLBACK pb_default_field_callback
#define temperature_v1_gpio_TemperatureSensorAdd_DEFAULT NULL

#define temperature_v1_gpio_TemperatureSensorAdded_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_pin,        1) \
X(a, STATIC,   SINGULAR, BOOL,     did_add,           2)
#define temperature_v1_gpio_TemperatureSensorAdded_CALLBACK pb_default_field_callback
#define temperature_v1_gpio_TemperatureSensorAdded_DEFAULT NULL

#define temperature_v1_gpio_TemperatureSensorEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sensor_pin,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_celsius,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_fahrenheit,   3) \
X(a, STATIC,   SINGULAR, UENUM,    si_unit,           4)
#define temperature_v1_gpio_TemperatureSensorEvent_CALLBACK pb_default_field_callback
#define temperature_v1_gpio_TemperatureSensorEvent_DEFAULT NULL

extern const pb_msgdesc_t temperature_v1_gpio_TemperatureSensorAdd_msg;
extern const pb_msgdesc_t temperature_v1_gpio_TemperatureSensorAdded_msg;
extern const pb_msgdesc_t temperature_v1_gpio_TemperatureSensorEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define temperature_v1_gpio_TemperatureSensorAdd_fields &temperature_v1_gpio_TemperatureSensorAdd_msg
#define temperature_v1_gpio_TemperatureSensorAdded_fields &temperature_v1_gpio_TemperatureSensorAdded_msg
#define temperature_v1_gpio_TemperatureSensorEvent_fields &temperature_v1_gpio_TemperatureSensorEvent_msg

/* Maximum encoded size of messages (where known) */
/* temperature_v1_gpio_TemperatureSensorAdd_size depends on runtime parameters */
/* temperature_v1_gpio_TemperatureSensorAdded_size depends on runtime parameters */
/* temperature_v1_gpio_TemperatureSensorEvent_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
