/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Dec 13 12:44:19 2023. */

#include "wippersnapper/description.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_description_CreateDescriptionRequest, wippersnapper_description_CreateDescriptionRequest, AUTO)


PB_BIND(wippersnapper_description_CreateDescription, wippersnapper_description_CreateDescription, AUTO)


PB_BIND(wippersnapper_description_RegistrationComplete, wippersnapper_description_RegistrationComplete, AUTO)




