/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Thu Dec 14 13:03:52 2023. */

#include "wippersnapper/i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_i2c_I2CBusInit, wippersnapper_i2c_I2CBusInit, AUTO)


PB_BIND(wippersnapper_i2c_I2CBusInitResponse, wippersnapper_i2c_I2CBusInitResponse, AUTO)


PB_BIND(wippersnapper_i2c_I2CScan, wippersnapper_i2c_I2CScan, AUTO)


PB_BIND(wippersnapper_i2c_I2CScanResponse, wippersnapper_i2c_I2CScanResponse, 2)


PB_BIND(wippersnapper_i2c_I2CSensorProperties, wippersnapper_i2c_I2CSensorProperties, AUTO)


PB_BIND(wippersnapper_i2c_I2CInit, wippersnapper_i2c_I2CInit, AUTO)


PB_BIND(wippersnapper_i2c_I2CAdded, wippersnapper_i2c_I2CAdded, AUTO)


PB_BIND(wippersnapper_i2c_I2CUpdateResponse, wippersnapper_i2c_I2CUpdateResponse, AUTO)


PB_BIND(wippersnapper_i2c_I2CRemove, wippersnapper_i2c_I2CRemove, AUTO)


PB_BIND(wippersnapper_i2c_I2CRemoved, wippersnapper_i2c_I2CRemoved, AUTO)


PB_BIND(wippersnapper_i2c_I2CEvent, wippersnapper_i2c_I2CEvent, 2)




