/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Thu Dec 14 13:03:52 2023. */

#include "wippersnapper/sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_sensor_SensorProperties, wippersnapper_sensor_SensorProperties, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent, wippersnapper_sensor_SensorEvent, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEventColor, wippersnapper_sensor_SensorEvent_SensorEventColor, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEvent3DVector, wippersnapper_sensor_SensorEvent_SensorEvent3DVector, AUTO)


PB_BIND(wippersnapper_sensor_SensorEvent_SensorEventOrientation, wippersnapper_sensor_SensorEvent_SensorEventOrientation, AUTO)




