/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 at Wed Dec 13 12:44:19 2023. */

#include "wippersnapper/servo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wippersnapper_servo_ServoAdd, wippersnapper_servo_ServoAdd, AUTO)


PB_BIND(wippersnapper_servo_ServoAdded, wippersnapper_servo_ServoAdded, AUTO)


PB_BIND(wippersnapper_servo_ServoRemove, wippersnapper_servo_ServoRemove, AUTO)


PB_BIND(wippersnapper_servo_ServoWrite, wippersnapper_servo_ServoWrite, AUTO)



